apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: <account_id>.dkr.ecr.ap-south-1.amazonaws.com/helloworld-app:1.0
        ports:
        - containerPort: 8080
